services:
  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    environment:
      - N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE=true
    volumes:
      - n8n_data:/home/node/.n8n
      - ./dist:/home/node/.n8n/custom/node_modules/n8n-nodes-datastone/dist
      - ./package.json:/home/node/.n8n/custom/node_modules/n8n-nodes-datastone/package.json

volumes:
  n8n_data:
